baseURL = 'https://herrscher0.github.io/'
languageCode = 'en-us'
title = 'ä¸€ åª ğŸµ é±¼'
theme = 'PaperMod'

publishDir = "docs"

[params.profileMode]
enabled = true
title = "-é˜¿è•Šå¨…Aria-"
subtitle = "æ˜¯å”±æ­Œçš„å°ç¾äººé±¼"
imageUrl = "/profile.jpg"
imageTitle = "å½»åº•ç–¯ç‹‚ï¼ï¼"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "ç‚¹æ­Œ"
  url = "/songs/"

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archives/"

[[params.socialIcons]]
name = "bilibili"
url = "https://live.bilibili.com/594461"

[[params.socialIcons]]
name = "qq"
url = "https://jq.qq.com/?_wv=1027&k=NId3lhYg"

[[params.socialIcons]]
name = "email"
url = "https://www.tapechat.net/uu/RGIAYJ/ZIOON5KJ?uid=7195666"

[outputs]
    home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
    identifier = "ç‚¹æ­Œ"
    name = "ç‚¹æ­Œ"
    url = "/songs/"
    weight = 10
#[[menu.main]]
#    identifier = "tags"
#    name = "tags"
#    url = "/tags/"
#    weight = 20
[[menu.main]]
    identifier = "search"
    name = "search"
    url = "/search/"
    weight = 40
[[menu.main]]
    identifier = "archives"
    name = "archives"
    url = "/archives/"
    weight = 30